### ISSUE TITLE
Running it fails from command line

### ISSUE THREAD

**Issue by rajma** [nbarbettini/oidc-debugger#40]
New to .Net. When I execute the instructions in README for build it works fine. Run in the project root directory fails with the complaint that it cannot find the project file.
Run in the project directory fails with missing module
Application startup exception: System.AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\rajan\AppData\Local\Temp\ofl0j3la.nwd:83:19)
    at __webpack_require__ (C:\Users\rajan\AppData\Local\Temp\ofl0j3la.nwd:20:30)
    at createWebpackDevServer (C:\Users\rajan\AppData\Local\Temp\ofl0j3la.nwd:62:26)
    at C:\Users\rajan\AppData\Local\Temp\k2ntgyr3.s5v:114:19
    at IncomingMessage.<anonymous> (C:\Users\rajan\AppData\Local\Temp\k2ntgyr3.s5v:133:38)
    at emitNone (events.js:86:13)
Current directory is: C:\Users\rajan\github\oidc-debugger\OidcDebugger

In windows 10 dotnet 2.1.401

**Comment by felpel** [comment]
@rajma I was able to run the project by doing `npm install` prior to `dotnet run`.
